### ISSUE TITLE
Import fails

### ISSUE THREAD

**Issue by wizard32** [BloodHoundAD/BARK#4]
Importing script as indicated under your README file it fails with the following error:
```
At C:\Users\user\Desktop\Exclusions\BARK\BARK.ps1:4641 char:1
+ }
+ ~
Unexpected token '}' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : UnexpectedToken
```

Downloading the repo from https://github.com/f-bader/BARK.git it works.

**Comment by andyrobbins** [comment]
Thank you for opening the issue, I forgot to close this issue after fixing it a while ago
